name: home
timestamp: 1508072231
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1506016058
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-3898: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-3903: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-7155: Copyright
  social:
    social-3004: Social
  branding:
    branding-7848: Branding
  mobile-menu:
    mobile-menu-9981: 'Mobile Menu'
inherit: {  }
