name: _offline
timestamp: 1508072231
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1506016058
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1512: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-8024: Menu
  messages:
    system-messages-2459: 'System Messages'
  content:
    system-content-1684: 'Page Content'
  copyright:
    copyright-3836: Copyright
  spacer:
    spacer-2306: Spacer
  branding:
    branding-9016: Branding
  mobile-menu:
    mobile-menu-5649: Mobile-menu
inherit: {  }
