version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1506016058
layout:
  /header/:
    -
      - 'logo-1512 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-8024
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-2459
    -
      - system-content-1684
  /footer/:
    -
      - position-footer
    -
      - 'copyright-3836 40'
      - 'spacer-2306 30'
      - 'branding-9016 30'
  offcanvas:
    -
      - mobile-menu-5649
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
