name: _error
timestamp: 1508072231
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1506016058
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3492: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-8374: Menu
  messages:
    system-messages-8667: 'System Messages'
  content:
    system-content-2220: 'Page Content'
  copyright:
    copyright-8527: Copyright
  spacer:
    spacer-6682: Spacer
  branding:
    branding-4025: Branding
  mobile-menu:
    mobile-menu-3755: Mobile-menu
inherit: {  }
