version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1506016058
layout:
  /header/:
    -
      - 'logo-3492 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-8374
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-8667
    -
      - system-content-2220
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8527 40'
      - 'spacer-6682 30'
      - 'branding-4025 30'
  offcanvas:
    -
      - mobile-menu-3755
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
