name: _body_only
timestamp: 1508072231
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1506016058
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7378: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-3859: Menu
  messages:
    system-messages-3808: 'System Messages'
  content:
    system-content-7838: 'Page Content'
  copyright:
    copyright-6883: Copyright
  spacer:
    spacer-2466: Spacer
  branding:
    branding-9769: Branding
  mobile-menu:
    mobile-menu-3445: Mobile-menu
inherit: {  }
